### ISSUE TITLE
first init 

### ISSUE THREAD

**Issue by cverdela** [iGeeky/wolf#15]
"before all" hook in "{root}":
     AssertionError: res.body[[{"ok":false,"reason":"ERR_SERVER_ERROR","errmsg":"relation \"user\" does not exist"}]]: expected value to match json-schema '{"type":"object","properties":...' -> '{"ok":false,"reason":"ERR_SERV...'
      Missing required property: data
          schema: {"type":"object","properties":{"ok":{"type":"boolean","enum"...
          rule:   /required/2 -> "data"
      at Function.assert.jsonSchema (node_modules/chai-json-schema/index.js:183:44)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async adminLoginInternal (test/util/util.js:142:15)
      at async Context.<anonymous> (test/util/util.js:179:31)

**Comment by cverdela** [comment]
db.sql
