### ISSUE TITLE
wolf console  run npm install given error

### ISSUE THREAD

**Issue by laokan** [iGeeky/wolf#29]
wolf console
npm install give error
```
> yorkie@2.0.0 install /home/zhangpo/dev/hpems/wolf/console/node_modules/yorkie
> node bin/install.js

internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/home/zhangpo/dev/hpems/wolf/console/node_modules/yorkie/bin/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by iGeeky** [comment]
Hello, what is your environment like?
node version?
What is the npm version and the npm source you are using?
Are you in mainland China? If yes, you can try to set up npm. Or you can use vpn to install the package.
