### ISSUE TITLE
启用redis cache连接失败

### ISSUE THREAD

**Issue by midaug** [iGeeky/wolf#40]
版本：0.5.4

RBAC_REDIS_URL: redis://password@127.0.0.1:6379
尝试换为   redis://password@127.0.0.1:6379/0、 redis://h:password@127.0.0.1:6379 都无法成功

反复出现连接auth错误
[ERROR] The server returned "wrong number of arguments for 'auth' command". You are probably passing both username and password to Redis version 5 or below. You should only pass the 'password' option for Redis version 5 and under.
 [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
     at parseError (/opt/wolf/server/node_modules/redis-parser/lib/parser.js:179:12)
     at parseType (/opt/wolf/server/node_modules/redis-parser/lib/parser.js:302:14)
 [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required

**Comment by midaug** [comment]
已经解决
使用 redis://:password@127.0.0.1:6379/0 即可连接成功
参考 [https://stackoverflow.com/questions/67613484/redis-err-wrong-number-of-arguments-for-auth-command](https://stackoverflow.com/questions/67613484/redis-err-wrong-number-of-arguments-for-auth-command)
